CREATE TABLE Roles (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Departments (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL UNIQUE,
  IsActive BIT NOT NULL
);

CREATE TABLE WorkPolicies (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL UNIQUE,
  DailyExpectedMinutes INT NOT NULL,
  FixedLunchDeductionMinutes INT NOT NULL DEFAULT 45,
  LowGrossThresholdMinutes INT NOT NULL DEFAULT 300,
  SkipLunchDeductionForLowGross BIT NOT NULL DEFAULT 1,
  AllowManualBreakEdits BIT NOT NULL DEFAULT 0,
  TimesheetBackdateWindowDays INT NOT NULL DEFAULT 7,
  RequireMismatchReason BIT NOT NULL DEFAULT 1,
  IsActive BIT NOT NULL
);

CREATE TABLE Users (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  Email NVARCHAR(200) NOT NULL UNIQUE,
  EmployeeId NVARCHAR(50) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(500) NOT NULL,
  Role NVARCHAR(30) NOT NULL,
  IsActive BIT NOT NULL,
  DepartmentId UNIQUEIDENTIFIER NULL REFERENCES Departments(Id),
  WorkPolicyId UNIQUEIDENTIFIER NULL REFERENCES WorkPolicies(Id),
  ManagerId UNIQUEIDENTIFIER NULL REFERENCES Users(Id)
);

CREATE TABLE UserRoles (
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  RoleId UNIQUEIDENTIFIER NOT NULL REFERENCES Roles(Id),
  PRIMARY KEY (UserId, RoleId)
);

CREATE TABLE Projects (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(200) NOT NULL,
  Code NVARCHAR(50) NOT NULL UNIQUE,
  IsActive BIT NOT NULL,
  IsArchived BIT NOT NULL
);

CREATE TABLE ProjectMembers (
  ProjectId UNIQUEIDENTIFIER NOT NULL REFERENCES Projects(Id),
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  PRIMARY KEY (ProjectId, UserId)
);

CREATE TABLE TaskCategories (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL UNIQUE,
  IsActive BIT NOT NULL
);

CREATE TABLE WorkSessions (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  WorkDate DATE NOT NULL,
  CheckInAtUtc DATETIME2 NOT NULL,
  CheckOutAtUtc DATETIME2 NULL,
  Status INT NOT NULL,
  HasAttendanceException BIT NOT NULL
);
CREATE INDEX IX_WorkSessions_UserDate ON WorkSessions(UserId, WorkDate);

CREATE TABLE BreakEntries (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  WorkSessionId UNIQUEIDENTIFIER NOT NULL REFERENCES WorkSessions(Id),
  StartAtUtc DATETIME2 NOT NULL,
  EndAtUtc DATETIME2 NULL,
  DurationMinutes INT NOT NULL,
  IsManualEdit BIT NOT NULL
);
CREATE INDEX IX_BreakEntries_WorkSessionId ON BreakEntries(WorkSessionId);


CREATE TABLE Timesheets (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  WorkDate DATE NOT NULL,
  Status INT NOT NULL,
  SubmissionNotes NVARCHAR(2000) NULL,
  MismatchReason NVARCHAR(1000) NULL,
  ApprovedByUserId UNIQUEIDENTIFIER NULL REFERENCES Users(Id),
  SubmittedAtUtc DATETIME2 NULL,
  ApprovedAtUtc DATETIME2 NULL,
  RejectedAtUtc DATETIME2 NULL,
  ManagerComment NVARCHAR(1000) NULL,
  CONSTRAINT UQ_Timesheets_UserDate UNIQUE (UserId, WorkDate)
);

CREATE TABLE TimesheetEntries (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  TimesheetId UNIQUEIDENTIFIER NOT NULL REFERENCES Timesheets(Id),
  ProjectId UNIQUEIDENTIFIER NOT NULL REFERENCES Projects(Id),
  TaskCategoryId UNIQUEIDENTIFIER NOT NULL REFERENCES TaskCategories(Id),
  Minutes INT NOT NULL,
  Notes NVARCHAR(1000) NULL
);
CREATE INDEX IX_TimesheetEntries_TimesheetId ON TimesheetEntries(TimesheetId);
